apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: houcinereact.e
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service1
                port:
                  number: 3000
