apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-data
  resources:
    requests:
      storage: 1Gi
