apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: localhost:5050/mongo
          name: mongodb
          ports:
            - containerPort: 27017
          #startup probe
          startupProbe:
          # to execute a command in terminal
          exec:
            #check if mongodb deamon is running correctly
            command:
              - mongod
              - --version
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 1
          # env:
          #   # get the user name and password from the secret
          #   - name: MONGO_INITDB_ROOT_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongodb-secret
          #         key: mongo-root-username
          #   - name: MONGO_INITDB_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongodb-secret
          #         key: mongo-root-password
      # map to the persistentVolumeClaim Object
      volumes:
        - name: "mongodb-persistence"
          persistentVolumeClaim:
            claimName: "pvc-mongodb"
