apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
spec:
  clusterSize: 2
  kubernetesConfig:
    image: mongo
    imagePullPolicy: IfNotPresent
    securityContext:
      fsGroup: 1001
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 1Gi
    storageClass: csi-cephfs-sc
  # mongoDBSecurity:
  #   mongoDBAdminUser: admin
  #   password: password
  mongoDBMonitoring:
    enableExporter: true
    image: bitnami/mongodb-exporter:0.11.2-debian-10-r382
    imagePullPolicy: IfNotPresent
